<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.ul.miashs</groupId>
    <artifactId>parsing</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.bindist.dir>${project.basedir}/bindist</project.bindist.dir>
        <project.bin.classname>${project.groupId}.${project.artifactId}.Main</project.bin.classname>
        <project.bin.appname>parse</project.bin.appname>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.12.1</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
            <plugin>
                <!--  Ici, on crée une distribution binaire  -->
                <!--  Dossier de la bindist: ${project.basedir.bindist}  -->
                <!--  Nom du script : ${project.bin.appname}  -->
                <!--  Classe principale : ${project.bin.classname}  -->
                <!--  Commande : mvn package  -->
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>appassembler-maven-plugin</artifactId>
                <version>1.10</version>
                <configuration>
                    <assembleDirectory>${project.bindist.dir}</assembleDirectory>
                    <programs>
                        <program>
                            <mainClass>${project.bin.classname}</mainClass>
                            <id>${project.bin.appname}</id>
                        </program>
                    </programs>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <!--  Ici, on crée une distribution source  -->
                <!--
                 C'est une archive zip, qui pourra être déposée sur ARCHE
                -->
                <!--  Dossier : target  -->
                <!--  Configuration : voir zip.xml  -->
                <!--  Commande : mvn install  -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>make-zip</id>
                        <phase>install</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>zip.xml</descriptor>
                            </descriptors>
                            <appendAssemblyId>true</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!--  Ici, on utilise jflex  -->
            <!--  Conventions :  -->
            <!--
             le fichier source .lex est stocké dans le dossier src/main/cuplex/
            -->
            <!--
             le fichier généré Yylex.java est dans src/main/java
            -->
            <!--  Commande : mvn generate-sources  -->
            <!--  https://mvnrepository.com/artifact/de.jflex/jflex  -->
            <plugin>
                <groupId>de.jflex</groupId>
                <artifactId>jflex-maven-plugin</artifactId>
                <version>1.9.1</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <lexDefinitions>
                        <lexDefinition>src/main/cuplex</lexDefinition>
                    </lexDefinitions>
                    <outputDirectory>src/main/java</outputDirectory>
                    <verbose>true</verbose>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.vbmacher</groupId>
                <artifactId>cup-maven-plugin</artifactId>
                <version>11b-20160615-3</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <cupDefinition>
                                src/main/cuplex/Parser.cup
                            </cupDefinition>
                            <className>ParserCup</className>
                            <symbolsName>Sym</symbolsName>
                            <outputDirectory>src/main/java</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>com.github.vbmacher</groupId>
            <artifactId>java-cup-runtime</artifactId>
            <version>11b-20160615-3</version>
        </dependency>
    </dependencies>
</project>