
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.ul.miashs.compil.parsing;

import java_cup.runtime.*;
import fr.ul.miashs.compil.arbre.*;
import fr.ul.miashs.compil.tds.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\006\000\002\003\010\000\002\003\005" +
    "\000\002\003\007\000\002\004\004\000\002\004\003\000" +
    "\002\006\004\000\002\007\004\000\002\005\011\000\002" +
    "\005\011\000\002\010\003\000\002\010\002\000\002\011" +
    "\006\000\002\011\004\000\002\017\005\000\002\012\004" +
    "\000\002\012\004\000\002\012\002\000\002\014\005\000" +
    "\002\014\007\000\002\013\006\000\002\013\007\000\002" +
    "\013\007\000\002\013\007\000\002\013\011\000\002\013" +
    "\007\000\002\013\005\000\002\015\003\000\002\015\003" +
    "\000\002\015\005\000\002\015\006\000\002\015\005\000" +
    "\002\015\005\000\002\015\005\000\002\015\005\000\002" +
    "\015\005\000\002\016\005\000\002\016\005\000\002\016" +
    "\005\000\002\016\005\000\002\016\005\000\002\016\005" +
    "\000\002\020\003\000\002\020\002\000\002\021\005\000" +
    "\002\021\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\167\000\006\004\007\005\012\001\002\000\004\002" +
    "\171\001\002\000\004\027\163\001\002\000\006\004\154" +
    "\005\012\001\002\000\004\036\147\001\002\000\010\002" +
    "\ufff9\004\ufff9\005\ufff9\001\002\000\010\002\uffff\004\145" +
    "\005\012\001\002\000\004\036\143\001\002\000\004\027" +
    "\014\001\002\000\006\004\016\030\ufff3\001\002\000\004" +
    "\030\024\001\002\000\004\036\023\001\002\000\006\030" +
    "\ufff4\033\020\001\002\000\004\004\021\001\002\000\004" +
    "\036\022\001\002\000\006\030\ufff2\033\ufff2\001\002\000" +
    "\006\030\ufff1\033\ufff1\001\002\000\004\031\025\001\002" +
    "\000\020\004\uffed\006\uffed\010\uffed\011\uffed\012\uffed\032" +
    "\uffed\036\uffed\001\002\000\020\004\031\006\037\010\034" +
    "\011\033\012\030\032\035\036\032\001\002\000\020\004" +
    "\uffef\006\uffef\010\uffef\011\uffef\012\uffef\032\uffef\036\uffef" +
    "\001\002\000\004\027\137\001\002\000\004\036\132\001" +
    "\002\000\006\026\124\027\123\001\002\000\012\013\042" +
    "\027\043\035\041\036\044\001\002\000\004\027\115\001" +
    "\002\000\010\002\ufff5\004\ufff5\005\ufff5\001\002\000\020" +
    "\004\uffee\006\uffee\010\uffee\011\uffee\012\uffee\032\uffee\036" +
    "\uffee\001\002\000\004\027\040\001\002\000\012\013\042" +
    "\027\043\035\041\036\044\001\002\000\034\014\uffe3\015" +
    "\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3\023\uffe3" +
    "\024\uffe3\025\uffe3\030\uffe3\033\uffe3\034\uffe3\001\002\000" +
    "\004\027\113\001\002\000\012\013\042\027\043\035\041" +
    "\036\044\001\002\000\036\014\uffe2\015\uffe2\016\uffe2\017" +
    "\uffe2\020\uffe2\021\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2" +
    "\027\102\030\uffe2\033\uffe2\034\uffe2\001\002\000\026\014" +
    "\056\015\063\016\065\017\060\020\066\021\061\022\064" +
    "\023\067\024\057\025\062\001\002\000\004\030\047\001" +
    "\002\000\004\031\051\001\002\000\022\004\uffe7\006\uffe7" +
    "\007\054\010\uffe7\011\uffe7\012\uffe7\032\uffe7\036\uffe7\001" +
    "\002\000\020\004\uffed\006\uffed\010\uffed\011\uffed\012\uffed" +
    "\032\uffed\036\uffed\001\002\000\020\004\031\006\037\010" +
    "\034\011\033\012\030\032\053\036\032\001\002\000\022" +
    "\004\ufff0\006\ufff0\007\ufff0\010\ufff0\011\ufff0\012\ufff0\032" +
    "\ufff0\036\ufff0\001\002\000\004\031\051\001\002\000\020" +
    "\004\uffe6\006\uffe6\010\uffe6\011\uffe6\012\uffe6\032\uffe6\036" +
    "\uffe6\001\002\000\012\013\042\027\043\035\041\036\044" +
    "\001\002\000\012\013\042\027\043\035\041\036\044\001" +
    "\002\000\012\013\042\027\043\035\041\036\044\001\002" +
    "\000\012\013\042\027\043\035\041\036\044\001\002\000" +
    "\012\013\042\027\043\035\041\036\044\001\002\000\012" +
    "\013\042\027\043\035\041\036\044\001\002\000\012\013" +
    "\042\027\043\035\041\036\044\001\002\000\012\013\042" +
    "\027\043\035\041\036\044\001\002\000\012\013\042\027" +
    "\043\035\041\036\044\001\002\000\012\013\042\027\043" +
    "\035\041\036\044\001\002\000\014\014\056\015\063\016" +
    "\065\017\060\030\uffd7\001\002\000\014\014\056\015\063" +
    "\016\065\017\060\030\uffda\001\002\000\034\014\uffdd\015" +
    "\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd\023\uffdd" +
    "\024\uffdd\025\uffdd\030\uffdd\033\uffdd\034\uffdd\001\002\000" +
    "\014\014\056\015\063\016\065\017\060\030\uffd8\001\002" +
    "\000\034\014\uffde\015\uffde\016\065\017\060\020\uffde\021" +
    "\uffde\022\uffde\023\uffde\024\uffde\025\uffde\030\uffde\033\uffde" +
    "\034\uffde\001\002\000\014\014\056\015\063\016\065\017" +
    "\060\030\uffd5\001\002\000\014\014\056\015\063\016\065" +
    "\017\060\030\uffd9\001\002\000\034\014\uffdc\015\uffdc\016" +
    "\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc\023\uffdc\024\uffdc" +
    "\025\uffdc\030\uffdc\033\uffdc\034\uffdc\001\002\000\014\014" +
    "\056\015\063\016\065\017\060\030\uffd6\001\002\000\034" +
    "\014\uffdf\015\uffdf\016\065\017\060\020\uffdf\021\uffdf\022" +
    "\uffdf\023\uffdf\024\uffdf\025\uffdf\030\uffdf\033\uffdf\034\uffdf" +
    "\001\002\000\014\013\042\027\043\030\uffd3\035\041\036" +
    "\044\001\002\000\006\030\uffd4\033\107\001\002\000\004" +
    "\030\106\001\002\000\016\014\056\015\063\016\065\017" +
    "\060\030\uffd1\033\uffd1\001\002\000\034\014\uffe0\015\uffe0" +
    "\016\uffe0\017\uffe0\020\uffe0\021\uffe0\022\uffe0\023\uffe0\024" +
    "\uffe0\025\uffe0\030\uffe0\033\uffe0\034\uffe0\001\002\000\012" +
    "\013\042\027\043\035\041\036\044\001\002\000\016\014" +
    "\056\015\063\016\065\017\060\030\uffd2\033\uffd2\001\002" +
    "\000\014\014\056\015\063\016\065\017\060\030\112\001" +
    "\002\000\034\014\uffdb\015\uffdb\016\uffdb\017\uffdb\020\uffdb" +
    "\021\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\030\uffdb\033" +
    "\uffdb\034\uffdb\001\002\000\004\030\114\001\002\000\034" +
    "\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1\022" +
    "\uffe1\023\uffe1\024\uffe1\025\uffe1\030\uffe1\033\uffe1\034\uffe1" +
    "\001\002\000\012\013\042\027\043\035\041\036\044\001" +
    "\002\000\004\030\117\001\002\000\004\031\051\001\002" +
    "\000\020\004\uffe5\006\uffe5\010\uffe5\011\uffe5\012\uffe5\032" +
    "\uffe5\036\uffe5\001\002\000\014\014\056\015\063\016\065" +
    "\017\060\034\122\001\002\000\020\004\uffe4\006\uffe4\010" +
    "\uffe4\011\uffe4\012\uffe4\032\uffe4\036\uffe4\001\002\000\014" +
    "\013\042\027\043\030\uffd3\035\041\036\044\001\002\000" +
    "\012\013\042\027\043\035\041\036\044\001\002\000\014" +
    "\014\056\015\063\016\065\017\060\034\126\001\002\000" +
    "\020\004\uffea\006\uffea\010\uffea\011\uffea\012\uffea\032\uffea" +
    "\036\uffea\001\002\000\004\030\130\001\002\000\004\034" +
    "\131\001\002\000\020\004\uffe8\006\uffe8\010\uffe8\011\uffe8" +
    "\012\uffe8\032\uffe8\036\uffe8\001\002\000\006\026\134\034" +
    "\133\001\002\000\020\004\uffec\006\uffec\010\uffec\011\uffec" +
    "\012\uffec\032\uffec\036\uffec\001\002\000\004\035\135\001" +
    "\002\000\004\034\136\001\002\000\020\004\uffeb\006\uffeb" +
    "\010\uffeb\011\uffeb\012\uffeb\032\uffeb\036\uffeb\001\002\000" +
    "\012\013\042\027\043\035\041\036\044\001\002\000\014" +
    "\014\056\015\063\016\065\017\060\030\141\001\002\000" +
    "\004\034\142\001\002\000\020\004\uffe9\006\uffe9\010\uffe9" +
    "\011\uffe9\012\uffe9\032\uffe9\036\uffe9\001\002\000\004\027" +
    "\ufff8\001\002\000\010\002\ufffa\004\ufffa\005\ufffa\001\002" +
    "\000\004\036\146\001\002\000\004\027\ufff7\001\002\000" +
    "\010\026\151\027\ufff7\034\150\001\002\000\006\004\ufffc" +
    "\005\ufffc\001\002\000\004\035\152\001\002\000\004\034" +
    "\153\001\002\000\006\004\ufffb\005\ufffb\001\002\000\004" +
    "\036\156\001\002\000\010\002\001\004\145\005\012\001" +
    "\002\000\010\026\160\027\ufff7\034\157\001\002\000\006" +
    "\004\ufffe\005\ufffe\001\002\000\004\035\161\001\002\000" +
    "\004\034\162\001\002\000\006\004\ufffd\005\ufffd\001\002" +
    "\000\006\004\016\030\ufff3\001\002\000\004\030\165\001" +
    "\002\000\004\031\166\001\002\000\020\004\uffed\006\uffed" +
    "\010\uffed\011\uffed\012\uffed\032\uffed\036\uffed\001\002\000" +
    "\020\004\031\006\037\010\034\011\033\012\030\032\170" +
    "\036\032\001\002\000\010\002\ufff6\004\ufff6\005\ufff6\001" +
    "\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\167\000\016\002\003\003\005\004\010\005\007\006" +
    "\004\007\012\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\004\154\005\007\006\004\007\012\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\005\143\006\004" +
    "\007\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\010\014\011\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\025\001\001\000\006\013\026\014\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\015\120\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\015\044\016\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\015\110\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\017\047\001" +
    "\001\000\002\001\001\000\004\012\051\001\001\000\006" +
    "\013\026\014\035\001\001\000\002\001\001\000\004\017" +
    "\054\001\001\000\002\001\001\000\004\015\100\001\001" +
    "\000\004\015\077\001\001\000\004\015\076\001\001\000" +
    "\004\015\075\001\001\000\004\015\074\001\001\000\004" +
    "\015\073\001\001\000\004\015\072\001\001\000\004\015" +
    "\071\001\001\000\004\015\070\001\001\000\004\015\067" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\015\104\020\103\021\102\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\015\107\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\044\016\115\001\001\000\002" +
    "\001\001\000\004\017\117\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\015\104\020\126" +
    "\021\102\001\001\000\004\015\124\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\137\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\005\143\006\004\007\012\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\163\011" +
    "\016\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\166\001\001\000\006\013\026\014\035\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public Table tds = new Table();
    public Symbole scopeActuel = null;
    public int nbParamActuel = 0;
    public int nbVarLocActuel = 0;


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCup$actions {
  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action_part00000000(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programme ::= liste_declarations_globales liste_fonctions 
            {
              Prog RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> ld = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int lfleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Noeud> lf = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Prog prog = new Prog();
        for (Noeud f : lf) prog.ajouterUnFils(f);
        System.out.println("=== Arbre abstrait ===");
        TxtAfficheur.afficher(prog);
        System.out.println("\n=== Table des symboles ===");
        System.out.println(parser.tds);
        RESULT = prog;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programme",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programme EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Prog start_val = (Prog)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programme ::= liste_fonctions 
            {
              Prog RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Noeud> lf = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Prog prog = new Prog();
        for (Noeud f : lf) prog.ajouterUnFils(f);
        System.out.println("=== Arbre abstrait ===");
        TxtAfficheur.afficher(prog);
        System.out.println("\n=== Table des symboles ===");
        System.out.println(parser.tds);
        RESULT = prog;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programme",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // liste_declarations_globales ::= liste_declarations_globales TYPE_INT IDF POINT_VIRG 
            {
              ArrayList<Noeud> RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		ArrayList<Noeud> ld = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
        parser.tds.put(nom, s);
        RESULT = ld;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_declarations_globales",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // liste_declarations_globales ::= liste_declarations_globales TYPE_INT IDF AFF CONST_ENT POINT_VIRG 
            {
              ArrayList<Noeud> RESULT =null;
		int ldleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).left;
		int ldright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).right;
		ArrayList<Noeud> ld = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = new Symbole(nom, "int", "global", val, 0, 0, 0, null);
        parser.tds.put(nom, s);
        RESULT = ld;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_declarations_globales",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // liste_declarations_globales ::= TYPE_INT IDF POINT_VIRG 
            {
              ArrayList<Noeud> RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
        parser.tds.put(nom, s);
        RESULT = new ArrayList<>();
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_declarations_globales",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // liste_declarations_globales ::= TYPE_INT IDF AFF CONST_ENT POINT_VIRG 
            {
              ArrayList<Noeud> RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = new Symbole(nom, "int", "global", val, 0, 0, 0, null);
        parser.tds.put(nom, s);
        RESULT = new ArrayList<>();
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_declarations_globales",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // liste_fonctions ::= liste_fonctions fonction 
            {
              ArrayList<Noeud> RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> lf = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Fonction f = (Fonction)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        lf.add(f);
        RESULT = lf;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_fonctions",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // liste_fonctions ::= fonction 
            {
              ArrayList<Noeud> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Fonction f = (Fonction)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        ArrayList<Noeud> lf = new ArrayList<>();
        lf.add(f);
        RESULT = lf;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_fonctions",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // entete_fonction_void ::= TYPE_VOID IDF 
            {
              String RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Symbole sf = new Symbole(nom, "void", "fonction", 0, 0, 0, 0, null);
        parser.tds.put(nom, sf);
        parser.scopeActuel    = sf;
        parser.nbParamActuel  = 0;
        parser.nbVarLocActuel = 0;
        RESULT = nom;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("entete_fonction_void",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // entete_fonction_int ::= TYPE_INT IDF 
            {
              String RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Symbole sf = new Symbole(nom, "int", "fonction", 0, 0, 0, 0, null);
        parser.tds.put(nom, sf);
        parser.scopeActuel    = sf;
        parser.nbParamActuel  = 0;
        parser.nbVarLocActuel = 0;
        RESULT = nom;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("entete_fonction_int",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // fonction ::= entete_fonction_void PAR_OUV liste_params PAR_FER ACCOLADE_OUV liste_instructions ACCOLADE_FER 
            {
              Fonction RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole sf = parser.tds.rechercherSymbole(nom);
        Fonction f = new Fonction(sf);
        for (Noeud instr : li) f.ajouterUnFils(instr);
        parser.scopeActuel = null;
        RESULT = f;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("fonction",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // fonction ::= entete_fonction_int PAR_OUV liste_params PAR_FER ACCOLADE_OUV liste_instructions ACCOLADE_FER 
            {
              Fonction RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole sf = parser.tds.rechercherSymbole(nom);
        Fonction f = new Fonction(sf);
        for (Noeud instr : li) f.ajouterUnFils(instr);
        parser.scopeActuel = null;
        RESULT = f;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("fonction",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // liste_params ::= params 
            {
              ArrayList<Symbole> RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  RESULT = lp; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_params",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // liste_params ::= 
            {
              ArrayList<Symbole> RESULT =null;
		  RESULT = new ArrayList<>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_params",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // params ::= params VIRGULE TYPE_INT IDF 
            {
              ArrayList<Symbole> RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Symbole sp = new Symbole(nom, "int", "param", parser.nbParamActuel++, parser.scopeActuel);
        parser.tds.put(nom, sp);
        lp.add(sp);
        RESULT = lp;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("params",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // params ::= TYPE_INT IDF 
            {
              ArrayList<Symbole> RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        ArrayList<Symbole> lp = new ArrayList<>();
        Symbole sp = new Symbole(nom, "int", "param", parser.nbParamActuel++, parser.scopeActuel);
        parser.tds.put(nom, sp);
        lp.add(sp);
        RESULT = lp;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("params",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // bloc ::= ACCOLADE_OUV liste_instructions ACCOLADE_FER 
            {
              Bloc RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Bloc b = new Bloc();
        for (Noeud instr : li) b.ajouterUnFils(instr);
        RESULT = b;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloc",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // liste_instructions ::= liste_instructions instruction 
            {
              ArrayList<Noeud> RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud i = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        li.add(i);
        RESULT = li;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_instructions",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // liste_instructions ::= liste_instructions declaration_locale 
            {
              ArrayList<Noeud> RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        if (d != null) li.add(d);
        RESULT = li;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_instructions",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // liste_instructions ::= 
            {
              ArrayList<Noeud> RESULT =null;
		  RESULT = new ArrayList<>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_instructions",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaration_locale ::= TYPE_INT IDF POINT_VIRG 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = new Symbole(nom, "int", "local", parser.nbVarLocActuel++, parser.scopeActuel);
        parser.tds.put(nom, s);
        RESULT = null;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaration_locale",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaration_locale ::= TYPE_INT IDF AFF CONST_ENT POINT_VIRG 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = new Symbole(nom, "int", "local", parser.nbVarLocActuel++, parser.scopeActuel);
        parser.tds.put(nom, s);
        Idf idf = new Idf(s);
        Affectation aff = new Affectation();
        aff.setFilsGauche(idf);
        aff.setFilsDroit(new Const(val));
        RESULT = aff;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("declaration_locale",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // instruction ::= IDF AFF expression POINT_VIRG 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        Idf idf = new Idf(s);
        Affectation aff = new Affectation();
        aff.setFilsGauche(idf);
        aff.setFilsDroit(e);
        RESULT = aff;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // instruction ::= ECRIRE PAR_OUV expression PAR_FER POINT_VIRG 
            {
              Noeud RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		
        Ecrire ecr = new Ecrire();
        ecr.setLeFils(e);
        RESULT = ecr;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // instruction ::= IDF PAR_OUV liste_args PAR_FER POINT_VIRG 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        Appel ap = new Appel(s);
        for (Noeud arg : la) ap.ajouterUnFils(arg);
        RESULT = ap;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // instruction ::= SI PAR_OUV condition PAR_FER bloc 
            {
              Noeud RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud c = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int alorsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int alorsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Bloc alors = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Si si = new Si();
        si.setCondition(c);
        si.setBlocAlors(alors);
        si.setBlocSinon(new Bloc());
        RESULT = si;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // instruction ::= SI PAR_OUV condition PAR_FER bloc SINON bloc 
            {
              Noeud RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		Noeud c = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int alorsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int alorsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Bloc alors = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int sinonleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int sinonright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Bloc sinon = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Si si = new Si();
        si.setCondition(c);
        si.setBlocAlors(alors);
        si.setBlocSinon(sinon);
        RESULT = si;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // instruction ::= TANTQUE PAR_OUV condition PAR_FER bloc 
            {
              Noeud RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud c = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Bloc b = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        TantQue tq = new TantQue();
        tq.setCondition(c);
        tq.setBloc(b);
        RESULT = tq;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // instruction ::= RETOUR expression POINT_VIRG 
            {
              Noeud RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Retour ret = new Retour(parser.scopeActuel);
        ret.setLeFils(e);
        RESULT = ret;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expression ::= CONST_ENT 
            {
              Noeud RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  RESULT = new Const(v); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expression ::= IDF 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        RESULT = new Idf(s);
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expression ::= LIRE PAR_OUV PAR_FER 
            {
              Noeud RESULT =null;
		  RESULT = new Lire(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expression ::= IDF PAR_OUV liste_args PAR_FER 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        Appel ap = new Appel(s);
        for (Noeud arg : la) ap.ajouterUnFils(arg);
        RESULT = ap;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expression ::= expression PLUS expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Plus p = new Plus();
        p.setFilsGauche(g);
        p.setFilsDroit(d);
        RESULT = p;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expression ::= expression MOINS expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Moins m = new Moins();
        m.setFilsGauche(g);
        m.setFilsDroit(d);
        RESULT = m;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expression ::= expression MUL expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Multiplication mul = new Multiplication();
        mul.setFilsGauche(g);
        mul.setFilsDroit(d);
        RESULT = mul;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expression ::= expression DIV expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Division div = new Division();
        div.setFilsGauche(g);
        div.setFilsDroit(d);
        RESULT = div;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expression ::= PAR_OUV expression PAR_FER 
            {
              Noeud RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		  RESULT = e; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condition ::= expression SUP expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Superieur s = new Superieur(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condition ::= expression INF expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Inferieur s = new Inferieur(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condition ::= expression SUP_EG expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  SuperieurEgal s = new SuperieurEgal(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condition ::= expression INF_EG expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  InferieurEgal s = new InferieurEgal(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // condition ::= expression EGAL expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Egal s = new Egal(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // condition ::= expression DIFF expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Different s = new Different(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // liste_args ::= args 
            {
              ArrayList<Noeud> RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  RESULT = la; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_args",14, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // liste_args ::= 
            {
              ArrayList<Noeud> RESULT =null;
		  RESULT = new ArrayList<>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_args",14, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // args ::= args VIRGULE expression 
            {
              ArrayList<Noeud> RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        la.add(e);
        RESULT = la;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("args",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // args ::= expression 
            {
              ArrayList<Noeud> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        ArrayList<Noeud> la = new ArrayList<>();
        la.add(e);
        RESULT = la;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("args",15, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
              return CUP$ParserCup$do_action_part00000000(
                               CUP$ParserCup$act_num,
                               CUP$ParserCup$parser,
                               CUP$ParserCup$stack,
                               CUP$ParserCup$top);
    }
}

}
