
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.ul.miashs.compil.parsing;

import java_cup.runtime.*;
import fr.ul.miashs.compil.arbre.*;
import fr.ul.miashs.compil.tds.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\051\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\003\000\002\016\002\000\002\004\013" +
    "\000\002\017\002\000\002\004\013\000\002\005\003\000" +
    "\002\005\002\000\002\006\006\000\002\006\004\000\002" +
    "\013\005\000\002\007\004\000\002\007\002\000\002\010" +
    "\006\000\002\010\007\000\002\010\007\000\002\010\007" +
    "\000\002\010\011\000\002\010\007\000\002\010\005\000" +
    "\002\011\003\000\002\011\003\000\002\011\005\000\002" +
    "\011\006\000\002\011\005\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\012\005" +
    "\000\002\012\005\000\002\012\005\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\014\003\000\002" +
    "\014\002\000\002\015\005\000\002\015\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\142\000\006\004\006\005\010\001\002\000\004\002" +
    "\144\001\002\000\010\002\ufffe\004\ufffe\005\ufffe\001\002" +
    "\000\004\036\134\001\002\000\010\002\001\004\006\005" +
    "\010\001\002\000\004\036\011\001\002\000\004\027\ufffd" +
    "\001\002\000\004\027\013\001\002\000\006\004\015\030" +
    "\ufff8\001\002\000\004\030\023\001\002\000\004\036\022" +
    "\001\002\000\006\030\ufff9\033\017\001\002\000\004\004" +
    "\020\001\002\000\004\036\021\001\002\000\006\030\ufff7" +
    "\033\ufff7\001\002\000\006\030\ufff6\033\ufff6\001\002\000" +
    "\004\031\024\001\002\000\016\006\ufff3\010\ufff3\011\ufff3" +
    "\012\ufff3\032\ufff3\036\ufff3\001\002\000\016\006\030\010" +
    "\027\011\032\012\034\032\033\036\031\001\002\000\016" +
    "\006\ufff4\010\ufff4\011\ufff4\012\ufff4\032\ufff4\036\ufff4\001" +
    "\002\000\004\027\127\001\002\000\004\027\101\001\002" +
    "\000\006\026\073\027\072\001\002\000\012\013\037\027" +
    "\040\035\036\036\041\001\002\000\010\002\ufffc\004\ufffc" +
    "\005\ufffc\001\002\000\004\027\035\001\002\000\012\013" +
    "\037\027\040\035\036\036\041\001\002\000\034\014\uffeb" +
    "\015\uffeb\016\uffeb\017\uffeb\020\uffeb\021\uffeb\022\uffeb\023" +
    "\uffeb\024\uffeb\025\uffeb\030\uffeb\033\uffeb\034\uffeb\001\002" +
    "\000\004\027\066\001\002\000\012\013\037\027\040\035" +
    "\036\036\041\001\002\000\036\014\uffea\015\uffea\016\uffea" +
    "\017\uffea\020\uffea\021\uffea\022\uffea\023\uffea\024\uffea\025" +
    "\uffea\027\055\030\uffea\033\uffea\034\uffea\001\002\000\014" +
    "\014\044\015\046\016\045\017\047\030\043\001\002\000" +
    "\004\034\054\001\002\000\012\013\037\027\040\035\036" +
    "\036\041\001\002\000\012\013\037\027\040\035\036\036" +
    "\041\001\002\000\012\013\037\027\040\035\036\036\041" +
    "\001\002\000\012\013\037\027\040\035\036\036\041\001" +
    "\002\000\034\014\uffe4\015\uffe4\016\uffe4\017\uffe4\020\uffe4" +
    "\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\030\uffe4\033" +
    "\uffe4\034\uffe4\001\002\000\034\014\uffe6\015\uffe6\016\045" +
    "\017\047\020\uffe6\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025" +
    "\uffe6\030\uffe6\033\uffe6\034\uffe6\001\002\000\034\014\uffe5" +
    "\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022\uffe5\023" +
    "\uffe5\024\uffe5\025\uffe5\030\uffe5\033\uffe5\034\uffe5\001\002" +
    "\000\034\014\uffe7\015\uffe7\016\045\017\047\020\uffe7\021" +
    "\uffe7\022\uffe7\023\uffe7\024\uffe7\025\uffe7\030\uffe7\033\uffe7" +
    "\034\uffe7\001\002\000\016\006\ufff1\010\ufff1\011\ufff1\012" +
    "\ufff1\032\ufff1\036\ufff1\001\002\000\014\013\037\027\040" +
    "\030\uffdb\035\036\036\041\001\002\000\006\030\uffdc\033" +
    "\062\001\002\000\004\030\061\001\002\000\016\014\044" +
    "\015\046\016\045\017\047\030\uffd9\033\uffd9\001\002\000" +
    "\034\014\uffe8\015\uffe8\016\uffe8\017\uffe8\020\uffe8\021\uffe8" +
    "\022\uffe8\023\uffe8\024\uffe8\025\uffe8\030\uffe8\033\uffe8\034" +
    "\uffe8\001\002\000\012\013\037\027\040\035\036\036\041" +
    "\001\002\000\016\014\044\015\046\016\045\017\047\030" +
    "\uffda\033\uffda\001\002\000\014\014\044\015\046\016\045" +
    "\017\047\030\065\001\002\000\034\014\uffe3\015\uffe3\016" +
    "\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3\023\uffe3\024\uffe3" +
    "\025\uffe3\030\uffe3\033\uffe3\034\uffe3\001\002\000\004\030" +
    "\067\001\002\000\034\014\uffe9\015\uffe9\016\uffe9\017\uffe9" +
    "\020\uffe9\021\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9\030" +
    "\uffe9\033\uffe9\034\uffe9\001\002\000\014\014\044\015\046" +
    "\016\045\017\047\034\071\001\002\000\016\006\uffec\010" +
    "\uffec\011\uffec\012\uffec\032\uffec\036\uffec\001\002\000\014" +
    "\013\037\027\040\030\uffdb\035\036\036\041\001\002\000" +
    "\012\013\037\027\040\035\036\036\041\001\002\000\014" +
    "\014\044\015\046\016\045\017\047\034\075\001\002\000" +
    "\016\006\ufff2\010\ufff2\011\ufff2\012\ufff2\032\ufff2\036\ufff2" +
    "\001\002\000\004\030\077\001\002\000\004\034\100\001" +
    "\002\000\016\006\ufff0\010\ufff0\011\ufff0\012\ufff0\032\ufff0" +
    "\036\ufff0\001\002\000\012\013\037\027\040\035\036\036" +
    "\041\001\002\000\026\014\044\015\046\016\045\017\047" +
    "\020\117\021\114\022\116\023\120\024\113\025\115\001" +
    "\002\000\004\030\104\001\002\000\004\031\106\001\002" +
    "\000\020\006\uffef\007\111\010\uffef\011\uffef\012\uffef\032" +
    "\uffef\036\uffef\001\002\000\016\006\ufff3\010\ufff3\011\ufff3" +
    "\012\ufff3\032\ufff3\036\ufff3\001\002\000\016\006\030\010" +
    "\027\011\032\012\034\032\110\036\031\001\002\000\020" +
    "\006\ufff5\007\ufff5\010\ufff5\011\ufff5\012\ufff5\032\ufff5\036" +
    "\ufff5\001\002\000\004\031\106\001\002\000\016\006\uffee" +
    "\010\uffee\011\uffee\012\uffee\032\uffee\036\uffee\001\002\000" +
    "\012\013\037\027\040\035\036\036\041\001\002\000\012" +
    "\013\037\027\040\035\036\036\041\001\002\000\012\013" +
    "\037\027\040\035\036\036\041\001\002\000\012\013\037" +
    "\027\040\035\036\036\041\001\002\000\012\013\037\027" +
    "\040\035\036\036\041\001\002\000\012\013\037\027\040" +
    "\035\036\036\041\001\002\000\014\014\044\015\046\016" +
    "\045\017\047\030\uffdf\001\002\000\014\014\044\015\046" +
    "\016\045\017\047\030\uffe2\001\002\000\014\014\044\015" +
    "\046\016\045\017\047\030\uffe0\001\002\000\014\014\044" +
    "\015\046\016\045\017\047\030\uffdd\001\002\000\014\014" +
    "\044\015\046\016\045\017\047\030\uffe1\001\002\000\014" +
    "\014\044\015\046\016\045\017\047\030\uffde\001\002\000" +
    "\012\013\037\027\040\035\036\036\041\001\002\000\004" +
    "\030\131\001\002\000\004\031\106\001\002\000\016\006" +
    "\uffed\010\uffed\011\uffed\012\uffed\032\uffed\036\uffed\001\002" +
    "\000\010\002\uffff\004\uffff\005\uffff\001\002\000\004\027" +
    "\ufffb\001\002\000\004\027\136\001\002\000\006\004\015" +
    "\030\ufff8\001\002\000\004\030\140\001\002\000\004\031" +
    "\141\001\002\000\016\006\ufff3\010\ufff3\011\ufff3\012\ufff3" +
    "\032\ufff3\036\ufff3\001\002\000\016\006\030\010\027\011" +
    "\032\012\034\032\143\036\031\001\002\000\010\002\ufffa" +
    "\004\ufffa\005\ufffa\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\142\000\010\002\003\003\006\004\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\132\001\001\000\002\001\001\000\004\016\011\001" +
    "\001\000\002\001\001\000\006\005\013\006\015\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\024\001\001\000" +
    "\004\010\025\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\067\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\041" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\052\001\001\000\004\011\051\001" +
    "\001\000\004\011\050\001\001\000\004\011\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\057\014\056" +
    "\015\055\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\062\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\057\014\075\015\055\001\001\000" +
    "\004\011\073\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\011\101\012\102\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\104\001\001\000\002\001\001\000" +
    "\004\007\106\001\001\000\004\010\025\001\001\000\002" +
    "\001\001\000\004\013\111\001\001\000\002\001\001\000" +
    "\004\011\125\001\001\000\004\011\124\001\001\000\004" +
    "\011\123\001\001\000\004\011\122\001\001\000\004\011" +
    "\121\001\001\000\004\011\120\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\011\101\012\127" +
    "\001\001\000\002\001\001\000\004\013\131\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\134\001\001" +
    "\000\002\001\001\000\006\005\136\006\015\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\141\001\001" +
    "\000\004\010\025\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public Table tds = new Table();
    public Symbole scopeActuel = null;
    public int nbParamActuel = 0;
    public int nbVarLocActuel = 0;


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCup$actions {
  private final ParserCup parser;

  /** Constructor */
  CUP$ParserCup$actions(ParserCup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action_part00000000(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCup$result;

      /* select the action based on the action number */
      switch (CUP$ParserCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programme ::= liste_fonctions 
            {
              Prog RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Noeud> lf = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Prog prog = new Prog();
        for (Noeud f : lf) {
            prog.ajouterUnFils(f);
        }
        System.out.println("=== Arbre abstrait ===");
        TxtAfficheur.afficher(prog);
        System.out.println("\n=== Table des symboles ===");
        System.out.println(parser.tds);
        RESULT = prog;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("programme",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programme EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Prog start_val = (Prog)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		RESULT = start_val;
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCup$parser.done_parsing();
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // liste_fonctions ::= liste_fonctions fonction 
            {
              ArrayList<Noeud> RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> lf = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Fonction f = (Fonction)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        lf.add(f);
        RESULT = lf;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_fonctions",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // liste_fonctions ::= fonction 
            {
              ArrayList<Noeud> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Fonction f = (Fonction)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        ArrayList<Noeud> lf = new ArrayList<>();
        lf.add(f);
        RESULT = lf;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_fonctions",1, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$0 ::= 
            {
              Fonction RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;

        Symbole sf = new Symbole(nom, "void", "fonction", 0, 0, 0, 0, null);
        parser.tds.put(nom, sf);
        parser.scopeActuel    = sf;
        parser.nbParamActuel  = 0;
        parser.nbVarLocActuel = 0;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("NT$0",12, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // fonction ::= TYPE_VOID IDF NT$0 PAR_OUV liste_params PAR_FER ACCOLADE_OUV liste_instructions ACCOLADE_FER 
            {
              Fonction RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Fonction) ((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole sf = parser.tds.rechercherSymbole(nom);
        Fonction f = new Fonction(sf);
        for (Noeud instr : li) {
            f.ajouterUnFils(instr);
        }
        parser.scopeActuel = null;
        RESULT = f;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("fonction",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$1 ::= 
            {
              Fonction RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;

        Symbole sf = new Symbole(nom, "int", "fonction", 0, 0, 0, 0, null);
        parser.tds.put(nom, sf);
        parser.scopeActuel    = sf;
        parser.nbParamActuel  = 0;
        parser.nbVarLocActuel = 0;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("NT$1",13, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // fonction ::= TYPE_INT IDF NT$1 PAR_OUV liste_params PAR_FER ACCOLADE_OUV liste_instructions ACCOLADE_FER 
            {
              Fonction RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Fonction) ((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-7)).value;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole sf = parser.tds.rechercherSymbole(nom);
        Fonction f = new Fonction(sf);
        for (Noeud instr : li) {
            f.ajouterUnFils(instr);
        }
        parser.scopeActuel = null;
        RESULT = f;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("fonction",2, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-8)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // liste_params ::= params 
            {
              ArrayList<Symbole> RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  RESULT = lp; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_params",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // liste_params ::= 
            {
              ArrayList<Symbole> RESULT =null;
		  RESULT = new ArrayList<>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_params",3, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // params ::= params VIRGULE TYPE_INT IDF 
            {
              ArrayList<Symbole> RESULT =null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		ArrayList<Symbole> lp = (ArrayList<Symbole>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Symbole sp = new Symbole(nom, "int", "param", parser.nbParamActuel++, parser.scopeActuel);
        parser.tds.put(nom, sp);
        lp.add(sp);
        RESULT = lp;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("params",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // params ::= TYPE_INT IDF 
            {
              ArrayList<Symbole> RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        ArrayList<Symbole> lp = new ArrayList<>();
        Symbole sp = new Symbole(nom, "int", "param", parser.nbParamActuel++, parser.scopeActuel);
        parser.tds.put(nom, sp);
        lp.add(sp);
        RESULT = lp;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("params",4, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bloc ::= ACCOLADE_OUV liste_instructions ACCOLADE_FER 
            {
              Bloc RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Bloc b = new Bloc();
        for (Noeud instr : li) {
            b.ajouterUnFils(instr);
        }
        RESULT = b;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("bloc",9, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // liste_instructions ::= liste_instructions instruction 
            {
              ArrayList<Noeud> RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> li = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud i = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        li.add(i);
        RESULT = li;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_instructions",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // liste_instructions ::= 
            {
              ArrayList<Noeud> RESULT =null;
		  RESULT = new ArrayList<>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_instructions",5, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // instruction ::= IDF AFF expression POINT_VIRG 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        Idf idf = new Idf(s);
        Affectation aff = new Affectation();
        aff.setFilsGauche(idf);
        aff.setFilsDroit(e);
        RESULT = aff;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // instruction ::= ECRIRE PAR_OUV expression PAR_FER POINT_VIRG 
            {
              Noeud RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		
        Ecrire ecr = new Ecrire();
        ecr.setLeFils(e);
        RESULT = ecr;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // instruction ::= IDF PAR_OUV liste_args PAR_FER POINT_VIRG 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        Appel ap = new Appel(s);
        for (Noeud arg : la) {
            ap.ajouterUnFils(arg);
        }
        RESULT = ap;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // instruction ::= SI PAR_OUV condition PAR_FER bloc 
            {
              Noeud RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud c = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int alorsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int alorsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Bloc alors = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Si si = new Si();
        si.setCondition(c);
        si.setBlocAlors(alors);
        si.setBlocSinon(new Bloc());
        RESULT = si;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // instruction ::= SI PAR_OUV condition PAR_FER bloc SINON bloc 
            {
              Noeud RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).right;
		Noeud c = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)).value;
		int alorsleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int alorsright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Bloc alors = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int sinonleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int sinonright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Bloc sinon = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Si si = new Si();
        si.setCondition(c);
        si.setBlocAlors(alors);
        si.setBlocSinon(sinon);
        RESULT = si;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-6)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // instruction ::= TANTQUE PAR_OUV condition PAR_FER bloc 
            {
              Noeud RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud c = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Bloc b = (Bloc)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        TantQue tq = new TantQue();
        tq.setCondition(c);
        tq.setBloc(b);
        RESULT = tq;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-4)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // instruction ::= RETOUR expression POINT_VIRG 
            {
              Noeud RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Retour ret = new Retour(e);
        RESULT = ret;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("instruction",6, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expression ::= CONST_ENT 
            {
              Noeud RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  RESULT = new Const(v); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expression ::= IDF 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        RESULT = new Idf(s);
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expression ::= LIRE PAR_OUV PAR_FER 
            {
              Noeud RESULT =null;
		  RESULT = new Lire(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expression ::= IDF PAR_OUV liste_args PAR_FER 
            {
              Noeud RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)).value;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		
        Symbole s = parser.tds.rechercherSymbole(nom);
        if (s == null) {
            s = new Symbole(nom, "int", "global", 0, 0, 0, 0, null);
            parser.tds.put(nom, s);
        }
        Appel ap = new Appel(s);
        for (Noeud arg : la) {
            ap.ajouterUnFils(arg);
        }
        RESULT = ap;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-3)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expression ::= expression PLUS expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Plus p = new Plus();
        p.setFilsGauche(g);
        p.setFilsDroit(d);
        RESULT = p;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression ::= expression MOINS expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Moins m = new Moins();
        m.setFilsGauche(g);
        m.setFilsDroit(d);
        RESULT = m;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression ::= expression MUL expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Multiplication mul = new Multiplication();
        mul.setFilsGauche(g);
        mul.setFilsDroit(d);
        RESULT = mul;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expression ::= expression DIV expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        Division div = new Division();
        div.setFilsGauche(g);
        div.setFilsDroit(d);
        RESULT = div;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expression ::= PAR_OUV expression PAR_FER 
            {
              Noeud RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-1)).value;
		  RESULT = e; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("expression",7, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condition ::= expression SUP expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Superieur s = new Superieur(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condition ::= expression INF expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Inferieur s = new Inferieur(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condition ::= expression SUP_EG expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  SuperieurEgal s = new SuperieurEgal(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condition ::= expression INF_EG expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  InferieurEgal s = new InferieurEgal(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condition ::= expression EGAL expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Egal s = new Egal(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condition ::= expression DIFF expression 
            {
              Noeud RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		Noeud g = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud d = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  Different s = new Different(); s.setFilsGauche(g); s.setFilsDroit(d); RESULT = s; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("condition",8, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // liste_args ::= args 
            {
              ArrayList<Noeud> RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		  RESULT = la; 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_args",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // liste_args ::= 
            {
              ArrayList<Noeud> RESULT =null;
		  RESULT = new ArrayList<>(); 
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("liste_args",10, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // args ::= args VIRGULE expression 
            {
              ArrayList<Noeud> RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).right;
		ArrayList<Noeud> la = (ArrayList<Noeud>)((java_cup.runtime.Symbol) CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        la.add(e);
        RESULT = la;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("args",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.elementAt(CUP$ParserCup$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // args ::= expression 
            {
              ArrayList<Noeud> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()).right;
		Noeud e = (Noeud)((java_cup.runtime.Symbol) CUP$ParserCup$stack.peek()).value;
		
        ArrayList<Noeud> la = new ArrayList<>();
        la.add(e);
        RESULT = la;
    
              CUP$ParserCup$result = parser.getSymbolFactory().newSymbol("args",11, ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCup$stack.peek()), RESULT);
            }
          return CUP$ParserCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCup$do_action(
    int                        CUP$ParserCup$act_num,
    java_cup.runtime.lr_parser CUP$ParserCup$parser,
    java.util.Stack            CUP$ParserCup$stack,
    int                        CUP$ParserCup$top)
    throws java.lang.Exception
    {
              return CUP$ParserCup$do_action_part00000000(
                               CUP$ParserCup$act_num,
                               CUP$ParserCup$parser,
                               CUP$ParserCup$stack,
                               CUP$ParserCup$top);
    }
}

}
