
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.ul.miashs.compil.parsing;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int IDF = 28;
  public static final int POINT_VIRG = 26;
  public static final int EGAL = 18;
  public static final int ACCOLADE_FER = 24;
  public static final int PLUS = 10;
  public static final int SUP = 14;
  public static final int LIRE = 9;
  public static final int PAR_OUV = 21;
  public static final int ECRIRE = 8;
  public static final int TYPE_INT = 2;
  public static final int TANTQUE = 6;
  public static final int AFF = 20;
  public static final int VIRGULE = 25;
  public static final int MOINS = 11;
  public static final int INF = 15;
  public static final int ACCOLADE_OUV = 23;
  public static final int SINON = 5;
  public static final int EOF = 0;
  public static final int CONST_ENT = 27;
  public static final int DIV = 13;
  public static final int SI = 4;
  public static final int error = 1;
  public static final int PAR_FER = 22;
  public static final int DIFF = 19;
  public static final int INF_EG = 17;
  public static final int RETOUR = 7;
  public static final int MUL = 12;
  public static final int SUP_EG = 16;
  public static final int TYPE_VOID = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TYPE_INT",
  "TYPE_VOID",
  "SI",
  "SINON",
  "TANTQUE",
  "RETOUR",
  "ECRIRE",
  "LIRE",
  "PLUS",
  "MOINS",
  "MUL",
  "DIV",
  "SUP",
  "INF",
  "SUP_EG",
  "INF_EG",
  "EGAL",
  "DIFF",
  "AFF",
  "PAR_OUV",
  "PAR_FER",
  "ACCOLADE_OUV",
  "ACCOLADE_FER",
  "VIRGULE",
  "POINT_VIRG",
  "CONST_ENT",
  "IDF"
  };
}

